name: datasci311
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip

  # core
  - numpy
  - pandas
  - scipy

  # viz
  - matplotlib
  - seaborn
  - plotly
  - python-kaleido

  # ML
  - scikit-learn
  - xgboost

  # notebooks
  - jupyterlab
  - ipykernel

  # useful IO
  - pyarrow
  - openpyxl

 # pip-only (best practice on Apple Silicon)
  - pip:
      - tensorflow==2.19.1
      - tensorflow-metal==1.2.0
